services:
  # MT5 Trading Bot - Optimized for Hostinger
  mt5-trading-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mt5-trading-bot
    restart: unless-stopped

    # Environment variables
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=UTC

    # Mount volumes for persistence
    volumes:
      - trading-logs:/app/logs
      - trading-data:/app/data

    # Resource limits for Hostinger VPS
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "0.5"

    # Health check
    healthcheck:
      test:
        [
          "CMD",
          "python3",
          "-c",
          "import requests; requests.get('http://localhost:8000/health', timeout=5)",
        ]
      interval: 60s
      timeout: 10s
      start_period: 120s
      retries: 3

    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"

# Named volumes for data persistence
volumes:
  trading-logs:
  trading-data:
